### ISSUE TITLE
Time Tracking Report - Worker Class

### ISSUE THREAD

**Issue by ruslan-korneev** [ruslan-korneev/glitch#11]
# class `TimeTracker`
## methods to get list of spent time. 
- [ ] method to get list of spent time for issues and merge-requests of certain project
- [ ] method to get list of spent time for issues and merge-requests by certain user
- [ ] method to get list of spent time for issues and merge-requests of certain project by certain user
- [ ] method to get list of spent time of one certain issue OR merge-request
- [ ] method to get list of spent time of one certain issue OR merge-request by certain user

> # there should be possibility to filter by:
>  - last week
>  - one specific date
>  - daterange (`from_date` - `to_date`)

> # Spent Time should be an instance of class `SpentTime` with attributes:
>  - `target: Target` (Target is `StrEnum` based class with 2 values: `Issue`, `MergeRequest`)
>  - `spent_time: int` (integer value in seconds)
>  - `posted_at: datetime | None` (date and time of spent-time post)
>  - `gitlab_profile_id: int | None` (id of author who posted spent time`

# Solution
To specify users who spent time for some issue/merge-request, we could parse an `{ProjectIssue/ProjectMergeRequest}.notes` body, if body ends with "time spent" we could catch the time and translate from human-readable to seconds. Example, how to get `ProjectIssue`,`ProjectMergeRequest`:
```python
from gitlab import Gitlab

gitlab = Gitlab(oauth=user.get_gitlab_access_token())
project = gitlab.projects.get(project_id)
project.issues         # returns list of `ProjectIssue`
project.mergerequests  # returns list of `ProjectMergeRequest`
```

> # IMPORTANT:
> we need exactly an instance of `ProjectIssue` or `ProjectMergeRequest`, not an instance of `Issue` or `MergeRequest` this is important

To collect all spent time without information about user we could use just existing information from gitlab-api, issue and merge-request object has method `time_stats`, where we can get time in seconds.
